vim.cmd[[
    hi DevIconJpeg                guibg=none guifg=#8ec07c
    hi DevIconZshenv              guibg=none guifg=#fb4934
    hi DevIconJpg                 guibg=none guifg=#8ec07c
    hi DevIconZshrc               guibg=none guifg=#fb4934
    hi DevIconNix                 guibg=none guifg=#ebdbb2
    hi DevIconBrewfile            guibg=none guifg=#ebdbb2
    hi DevIconDart                guibg=none guifg=#83a598
    hi DevIconCMakeLists          guibg=none guifg=#ebdbb2
    hi DevIconKsh                 guibg=none guifg=#b8bb26
    hi DevIconKotlin              guibg=none guifg=#d3869b
    hi DevIconLicense             guibg=none guifg=#ebdbb2
    hi DevIconDefault             guibg=none guifg=#ebdbb2
    hi DevIconKotlinScript        guibg=none guifg=#d3869b
    hi DevIconDockerfile          guibg=none guifg=#ebdbb2
    hi DevIconLeex                guibg=none guifg=#ebdbb2
    hi DevIconSln                 guibg=none guifg=#ebdbb2
    hi DevIconGemfile             guibg=none guifg=#fb4934
    hi DevIconSml                 guibg=none guifg=#ebdbb2
    hi DevIconSql                 guibg=none guifg=#b8bb26
    hi DevIconRmd                 guibg=none guifg=#ebdbb2
    hi DevIconMakefile            guibg=none guifg=#fabd2f
    hi DevIconMaterial            guibg=none guifg=#ebdbb2
    hi DevIconMd                  guibg=none guifg=#fabd2f
    hi DevIconGvimrc              guibg=none guifg=#b8bb26
    hi DevIconVimrc               guibg=none guifg=#b8bb26
    hi DevIconMixLock             guibg=none guifg=#ebdbb2
    hi DevIconBat                 guibg=none guifg=#ebdbb2
    hi DevIconMjs                 guibg=none guifg=#ebdbb2
    hi DevIconBmp                 guibg=none guifg=#8ec07c
    hi DevIconTcl                 guibg=none guifg=#ebdbb2
    hi DevIconMli                 guibg=none guifg=#ebdbb2
    hi DevIconMotoko              guibg=none guifg=#ebdbb2
    hi DevIconCobol               guibg=none guifg=#d3869b
    hi DevIconDump                guibg=none guifg=#ebdbb2
    hi DevIconTextResource        guibg=none guifg=#ebdbb2
    hi DevIconSvelte              guibg=none guifg=#fe8019
    hi DevIconTor                 guibg=none guifg=#d3869b
    hi DevIconClojure             guibg=none guifg=#ebdbb2
    hi DevIconC                   guibg=none guifg=#458588
    hi DevIconOPUS                guibg=none guifg=#ebdbb2
    hi DevIconClojureC            guibg=none guifg=#ebdbb2
    hi DevIconOpenTypeFont        guibg=none guifg=#83a598
    hi DevIconClojureJS           guibg=none guifg=#ebdbb2
    hi DevIconTxt                 guibg=none guifg=#a89984
    hi DevIconTex                 guibg=none guifg=#458588
    hi DevIconClojureDart         guibg=none guifg=#ebdbb2
    hi DevIconPackageLockJson     guibg=none guifg=#fabd2f
    hi DevIconVHDL                guibg=none guifg=#ebdbb2
    hi DevIconPdf                 guibg=none guifg=#fb4934
    hi DevIconEx                  guibg=none guifg=#ebdbb2
    hi DevIconWebmanifest         guibg=none guifg=#ebdbb2
    hi DevIconCMake               guibg=none guifg=#fabd2f
    hi DevIconWebp                guibg=none guifg=#ebdbb2
    hi DevIconLog                 guibg=none guifg=#ebdbb2
    hi DevIconJsx                 guibg=none guifg=#fabd2f
    hi DevIconCrystal             guibg=none guifg=#ebdbb2
    hi DevIconBash                guibg=none guifg=#b8bb26
    hi DevIconDsStore             guibg=none guifg=#ebdbb2
    hi DevIconGitLogo             guibg=none guifg=#ebdbb2
    hi DevIconPpt                 guibg=none guifg=#ebdbb2
    hi DevIconCsh                 guibg=none guifg=#ebdbb2
    hi DevIconPackageJson         guibg=none guifg=#fabd2f
    hi DevIconH                   guibg=none guifg=#83a598
    hi DevIconProlog              guibg=none guifg=#ebdbb2
    hi DevIconSlim                guibg=none guifg=#ebdbb2
    hi DevIconProcfile            guibg=none guifg=#ebdbb2
    hi DevIconCsv                 guibg=none guifg=#cc241d
    hi DevIconCxx                 guibg=none guifg=#ebdbb2
    hi DevIconPsd                 guibg=none guifg=#ebdbb2
    hi DevIconPy                  guibg=none guifg=#83a598
    hi DevIconPyc                 guibg=none guifg=#458588
    hi DevIconDesktopEntry        guibg=none guifg=#ebdbb2
    hi DevIconPyd                 guibg=none guifg=#ebdbb2
    hi DevIconGitCommit           guibg=none guifg=#ebdbb2
    hi DevIconCPlusPlus           guibg=none guifg=#ebdbb2
    hi DevIconRake                guibg=none guifg=#ebdbb2
    hi DevIconLess                guibg=none guifg=#ebdbb2
    hi DevIconRakefile            guibg=none guifg=#ebdbb2
    hi DevIconDrools              guibg=none guifg=#ebdbb2
    hi DevIconCpp                 guibg=none guifg=#458588
    hi DevIconConfiguration       guibg=none guifg=#ebdbb2
    hi DevIconLhs                 guibg=none guifg=#ebdbb2
    hi DevIconDropbox             guibg=none guifg=#83a597
    hi DevIconWebpack             guibg=none guifg=#ebdbb2
    hi DevIconRproj               guibg=none guifg=#ebdbb2
    hi DevIconSh                  guibg=none guifg=#ebdbb2
    hi DevIconEjs                 guibg=none guifg=#ebdbb2
    hi DevIconRs                  guibg=none guifg=#ebdbb2
    hi DevIconJl                  guibg=none guifg=#ebdbb2
    hi DevIconRss                 guibg=none guifg=#ebdbb2
    hi DevIconXls                 guibg=none guifg=#ebdbb2
    hi DevIconSettingsJson        guibg=none guifg=#ebdbb2
    hi DevIconYml                 guibg=none guifg=#b8bb26
    hi DevIconHbs                 guibg=none guifg=#ebdbb2
    hi DevIconEpp                 guibg=none guifg=#ebdbb2
    hi DevIconJs                  guibg=none guifg=#fabd2f
    hi DevIconFs                  guibg=none guifg=#ebdbb2
    hi DevIconHaml                guibg=none guifg=#b8bb26
    hi DevIconGDScript            guibg=none guifg=#ebdbb2
    hi DevIconD                   guibg=none guifg=#ebdbb2
    hi DevIconSig                 guibg=none guifg=#ebdbb2
    hi DevIconCson                guibg=none guifg=#ebdbb2
    hi DevIconNPMIgnore           guibg=none guifg=#ebdbb2
    hi DevIconR                   guibg=none guifg=#fb4934
    hi DevIconExs                 guibg=none guifg=#ebdbb2
    hi DevIconLock                guibg=none guifg=#ebdbb2
    hi DevIconErl                 guibg=none guifg=#ebdbb2
    hi DevIconErb                 guibg=none guifg=#ebdbb2
    hi DevIconFavicon             guibg=none guifg=#8ec07c
    hi DevIconFish                guibg=none guifg=#98971a
    hi DevIconVerilog             guibg=none guifg=#ebdbb2
    hi DevIconFennel              guibg=none guifg=#ebdbb2
    hi DevIconPhp                 guibg=none guifg=#d3869b
    hi DevIconDiff                guibg=none guifg=#ebdbb2
    hi DevIconJava                guibg=none guifg=#fe8019
    hi DevIconCs                  guibg=none guifg=#ebdbb2
    hi DevIconFsi                 guibg=none guifg=#ebdbb2
    hi DevIconHtml                guibg=none guifg=#fe8019
    hi DevIconFsscript            guibg=none guifg=#ebdbb2
    hi DevIconTsx                 guibg=none guifg=#ebdbb2
    hi DevIconHh                  guibg=none guifg=#ebdbb2
    hi DevIconTwig                guibg=none guifg=#ebdbb2
    hi DevIconMarkdown            guibg=none guifg=#fabd2f
    hi DevIconGemspec             guibg=none guifg=#ebdbb2
    hi DevIconFsx                 guibg=none guifg=#ebdbb2
    hi DevIconSass                guibg=none guifg=#ebdbb2
    hi DevIconGif                 guibg=none guifg=#b8bb26
    hi DevIconGitIgnore           guibg=none guifg=#fe8019
    hi DevIconBinaryGLTF          guibg=none guifg=#ebdbb2
    hi DevIconTerminal            guibg=none guifg=#ebdbb2
    hi DevIconFsharp              guibg=none guifg=#ebdbb2
    hi DevIconJson                guibg=none guifg=#fabd2f
    hi DevIconVim                 guibg=none guifg=#b8bb26
    hi DevIconGodotProject        guibg=none guifg=#ebdbb2
    hi DevIconSvg                 guibg=none guifg=#8ec07c
    hi DevIconGruntfile           guibg=none guifg=#ebdbb2
    hi DevIconXml                 guibg=none guifg=#b8bb26
    hi DevIconSystemVerilog       guibg=none guifg=#ebdbb2
    hi DevIconGulpfile            guibg=none guifg=#ebdbb2
    hi DevIconEex                 guibg=none guifg=#ebdbb2
    hi DevIconSuo                 guibg=none guifg=#ebdbb2
    hi DevIconHeex                guibg=none guifg=#ebdbb2
    hi DevIconDb                  guibg=none guifg=#ebdbb2
    hi DevIconScss                guibg=none guifg=#fabd2f
    hi DevIconConf                guibg=none guifg=#ebdbb2
    hi DevIconLua                 guibg=none guifg=#83a598
    hi DevIconAwk                 guibg=none guifg=#ebdbb2
    hi DevIconConfigRu            guibg=none guifg=#ebdbb2
    hi DevIconVagrantfile         guibg=none guifg=#ebdbb2
    hi DevIconPrisma              guibg=none guifg=#ebdbb2
    hi DevIconHrl                 guibg=none guifg=#ebdbb2
    hi DevIconSolidity            guibg=none guifg=#ebdbb2
    hi DevIconSwift               guibg=none guifg=#fe8019
    hi DevIconMdx                 guibg=none guifg=#ebdbb2
    hi DevIconHtm                 guibg=none guifg=#fe8019
    hi DevIconEdn                 guibg=none guifg=#ebdbb2
    hi DevIconAi                  guibg=none guifg=#ebdbb2
    hi DevIconMint                guibg=none guifg=#ebdbb2
    hi DevIconPyo                 guibg=none guifg=#ebdbb2
    hi DevIconNim                 guibg=none guifg=#ebdbb2
    hi DevIconHxx                 guibg=none guifg=#ebdbb2
    hi DevIconNodeModules         guibg=none guifg=#98971a
    hi DevIconDoc                 guibg=none guifg=#83a598
    hi DevIconPackedResource      guibg=none guifg=#ebdbb2
    hi DevIconImportConfiguration guibg=none guifg=#ebdbb2
    hi DevIconPl                  guibg=none guifg=#ebdbb2
    hi DevIconPm                  guibg=none guifg=#ebdbb2
    hi DevIconIni                 guibg=none guifg=#a89984
    hi DevIconMl                  guibg=none guifg=#ebdbb2
    hi DevIconPng                 guibg=none guifg=#8ec07c
    hi DevIconXul                 guibg=none guifg=#ebdbb2
    hi DevIconPromptPs1           guibg=none guifg=#ebdbb2
    hi DevIconIco                 guibg=none guifg=#8ec07c
    hi DevIconPsb                 guibg=none guifg=#ebdbb2
    hi DevIconTs                  guibg=none guifg=#83a598
    hi DevIconRb                  guibg=none guifg=#fb4934
    hi DevIconRlib                guibg=none guifg=#ebdbb2
    hi DevIconBashrc              guibg=none guifg=#b8bb26
    hi DevIconHs                  guibg=none guifg=#ebdbb2
    hi DevIconScala               guibg=none guifg=#ebdbb2
    hi DevIconHpp                 guibg=none guifg=#ebdbb2
    hi DevIconGitAttributes       guibg=none guifg=#ebdbb2
    hi DevIconStyl                guibg=none guifg=#ebdbb2
    hi DevIconNPMrc               guibg=none guifg=#b8bb26
    hi DevIconGitConfig           guibg=none guifg=#b8bb26
    hi DevIconCp                  guibg=none guifg=#ebdbb2
    hi DevIconGitlabCI            guibg=none guifg=#ebdbb2
    hi DevIconToml                guibg=none guifg=#b8bb26
    hi DevIconMustache            guibg=none guifg=#ebdbb2
    hi DevIconGo                  guibg=none guifg=#83a598
    hi DevIconGitModules          guibg=none guifg=#ebdbb2
    hi DevIconTextScene           guibg=none guifg=#ebdbb2
    hi DevIconCss                 guibg=none guifg=#fabd2f
    hi DevIconBabelrc             guibg=none guifg=#ebdbb2
    hi DevIconVue                 guibg=none guifg=#ebdbb2
    hi DevIconEnv                 guibg=none guifg=#ebdbb2
    hi DevIconZsh                 guibg=none guifg=#fb4934
    hi DevIconZig                 guibg=none guifg=#fabd2f
    hi DevIconBashProfile         guibg=none guifg=#b8bb26
    hi DevIconPp                  guibg=none guifg=#ebdbb2
    hi DevIconElm                 guibg=none guifg=#ebdbb2
    hi DevIconXcPlayground        guibg=none guifg=#ebdbb2
    hi DevIconYaml                guibg=none guifg=#b8bb26
    hi DevIconCoffee              guibg=none guifg=#cc241d
    hi DevIconZshprofile          guibg=none guifg=#fb4934
]]
